// <auto-generated>See comments in ITextDocument.g.cs.</auto-generated>
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member. Microsoft defines this COM API.

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace tom;

[ComImport]
[DefaultMember("Text")]
[Guid("8CC497C1-A1DF-11CE-8098-00AA0047BE5D")]
[TypeLibType(4288)]
public interface ITextSelection : ITextRange
{
	[DispId(0)]
	new string Text
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(0)]
		[return: MarshalAs(UnmanagedType.BStr)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(0)]
		[param: In]
		[param: MarshalAs(UnmanagedType.BStr)]
		set;
	}

	[DispId(513)]
	new int Char
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(513)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(513)]
		[param: In]
		set;
	}

	[DispId(514)]
	new ITextRange Duplicate
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(514)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
	}

	[DispId(515)]
	new ITextRange FormattedText
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(515)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(515)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(516)]
	new int Start
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(516)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(516)]
		[param: In]
		set;
	}

	[DispId(517)]
	new int End
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(517)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(517)]
		[param: In]
		set;
	}

	[DispId(518)]
	new ITextFont Font
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(518)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(518)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(519)]
	new ITextPara Para
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(519)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(519)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(520)]
	new int StoryLength
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(520)]
		get;
	}

	[DispId(521)]
	new int StoryType
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(521)]
		get;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(528)]
	new void Collapse([In] int bStart);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(529)]
	new int Expand([In] int Unit);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(530)]
	new int GetIndex([In] int Unit);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(531)]
	new void SetIndex([In] int Unit, [In] int Index, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(532)]
	new void SetRange([In] int cpActive, [In] int cpOther);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(533)]
	new int InRange([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(534)]
	new int InStory([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(535)]
	new int IsEqual([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(536)]
	new void Select();

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(537)]
	new int StartOf([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(544)]
	new int EndOf([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(545)]
	new int Move([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(546)]
	new int MoveStart([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(547)]
	new int MoveEnd([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(548)]
	new int MoveWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(549)]
	new int MoveStartWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(550)]
	new int MoveEndWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(551)]
	new int MoveUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(552)]
	new int MoveStartUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(553)]
	new int MoveEndUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(560)]
	new int FindText([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(561)]
	new int FindTextStart([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(562)]
	new int FindTextEnd([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(563)]
	new int Delete([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(564)]
	new void Cut([MarshalAs(UnmanagedType.Struct)] out object pVar);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(565)]
	new void Copy([MarshalAs(UnmanagedType.Struct)] out object pVar);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(566)]
	new void Paste([In][MarshalAs(UnmanagedType.Struct)] ref object pVar, [In] int Format);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(567)]
	new int CanPaste([In][MarshalAs(UnmanagedType.Struct)] ref object pVar, [In] int Format);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(568)]
	new int CanEdit();

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(569)]
	new void ChangeCase([In] int Type);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(576)]
	new void GetPoint([In] int Type, out int px, out int py);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(577)]
	new void SetPoint([In] int x, [In] int y, [In] int Type, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(578)]
	new void ScrollIntoView([In] int Value);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(579)]
	[return: MarshalAs(UnmanagedType.IUnknown)]
	new object GetEmbeddedObject();

	[DispId(257)]
	int Flags
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(257)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(257)]
		[param: In]
		set;
	}

	[DispId(258)]
	int Type
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(258)]
		get;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(259)]
	int MoveLeft([In] int Unit, [In] int Count, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(260)]
	int MoveRight([In] int Unit, [In] int Count, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(261)]
	int MoveUp([In] int Unit, [In] int Count, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(262)]
	int MoveDown([In] int Unit, [In] int Count, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(263)]
	int HomeKey([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(264)]
	int EndKey([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(265)]
	void TypeText([In][MarshalAs(UnmanagedType.BStr)] string bstr);
}
