// <auto-generated>See comments in ITextDocument.g.cs.</auto-generated>
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member. Microsoft defines this COM API.

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace tom;

[ComImport]
[TypeLibType(4288)]
[Guid("8CC497C2-A1DF-11CE-8098-00AA0047BE5D")]
[DefaultMember("Text")]
public interface ITextRange
{
	[DispId(0)]
	string Text
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(0)]
		[return: MarshalAs(UnmanagedType.BStr)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(0)]
		[param: In]
		[param: MarshalAs(UnmanagedType.BStr)]
		set;
	}

	[DispId(513)]
	int Char
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(513)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(513)]
		[param: In]
		set;
	}

	[DispId(514)]
	ITextRange Duplicate
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(514)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
	}

	[DispId(515)]
	ITextRange FormattedText
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(515)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(515)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(516)]
	int Start
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(516)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(516)]
		[param: In]
		set;
	}

	[DispId(517)]
	int End
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(517)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(517)]
		[param: In]
		set;
	}

	[DispId(518)]
	ITextFont Font
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(518)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(518)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(519)]
	ITextPara Para
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(519)]
		[return: MarshalAs(UnmanagedType.Interface)]
		get;
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(519)]
		[param: In]
		[param: MarshalAs(UnmanagedType.Interface)]
		set;
	}

	[DispId(520)]
	int StoryLength
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(520)]
		get;
	}

	[DispId(521)]
	int StoryType
	{
		[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
		[DispId(521)]
		get;
	}

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(528)]
	void Collapse([In] int bStart);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(529)]
	int Expand([In] int Unit);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(530)]
	int GetIndex([In] int Unit);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(531)]
	void SetIndex([In] int Unit, [In] int Index, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(532)]
	void SetRange([In] int cpActive, [In] int cpOther);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(533)]
	int InRange([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(534)]
	int InStory([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(535)]
	int IsEqual([In][MarshalAs(UnmanagedType.Interface)] ITextRange pRange);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(536)]
	void Select();

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(537)]
	int StartOf([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(544)]
	int EndOf([In] int Unit, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(545)]
	int Move([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(546)]
	int MoveStart([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(547)]
	int MoveEnd([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(548)]
	int MoveWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(549)]
	int MoveStartWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(550)]
	int MoveEndWhile([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(551)]
	int MoveUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(552)]
	int MoveStartUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(553)]
	int MoveEndUntil([In][MarshalAs(UnmanagedType.Struct)] ref object Cset, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(560)]
	int FindText([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(561)]
	int FindTextStart([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(562)]
	int FindTextEnd([In][MarshalAs(UnmanagedType.BStr)] string bstr, [In] int cch, [In] int Flags);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(563)]
	int Delete([In] int Unit, [In] int Count);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(564)]
	void Cut([MarshalAs(UnmanagedType.Struct)] out object pVar);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(565)]
	void Copy([MarshalAs(UnmanagedType.Struct)] out object pVar);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(566)]
	void Paste([In][MarshalAs(UnmanagedType.Struct)] ref object pVar, [In] int Format);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(567)]
	int CanPaste([In][MarshalAs(UnmanagedType.Struct)] ref object pVar, [In] int Format);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(568)]
	int CanEdit();

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(569)]
	void ChangeCase([In] int Type);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(576)]
	void GetPoint([In] int Type, out int px, out int py);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(577)]
	void SetPoint([In] int x, [In] int y, [In] int Type, [In] int Extend);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(578)]
	void ScrollIntoView([In] int Value);

	[MethodImpl(MethodImplOptions.InternalCall, MethodCodeType = MethodCodeType.Runtime)]
	[DispId(579)]
	[return: MarshalAs(UnmanagedType.IUnknown)]
	object GetEmbeddedObject();
}
